service: slack-bot
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  profile: ${env:AWS_PROFILE, 'sink'}
  runtime: nodejs20.x
  region: ${env:AWS_REGION, 'us-east-1'}
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SUPABASE_URL: ${env:SUPABASE_URL}
    SUPABASE_SERVICE_ROLE_KEY: ${env:SUPABASE_SERVICE_ROLE_KEY}

functions:
  slack:
    handler: src/app.handler
    events:
      - http:
          path: slack/events
          method: post

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
